packages:
    - "apps/*"
    - "packages/*"
    - "ndk"
    - "ndk-cache-dexie"
    - "ndk-cache-redis"
    - "ndk-cache-nostr"
    - "ndk-svelte"
    - "ndk-svelte-components"
    - "ndk-wallet"
    - "demos"
